apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  type: NodePort
  # this defines which pod are going to be represented by the service
  # network endpoint for other services or end users

  selector:
    app: webapp
    release: '0-5'
  ports:
    - port: 80 
      targetPort: 80
      nodePort: 30080 

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  type: NodePort
  # this defines which pod are going to be represented by the service
  # network endpoint for other services or end users

  selector:
    app: queue
  ports:
    - port: 8161
      targetPort: 8161
      nodePort: 30010
