# the storage that is needed
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  #  binding process takes place to match all that match the spec requirements
  storageClassName: mylocalstorage # to determine what type of storage that is needed (SSD / HDD type of storage)
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---
# the storage that is implemented
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage
spec:
  storageClassName: mylocalstorage
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/newDirectory/"
    type: DirectoryOrCreate
