kind: ConfigMap
apiVersion: v1
metadata:
  name: global-database-config
  namespace: default
data:
  # used with volume mounting
  database.properties: |
    database.url=https://updated-server.somewhere.come:3306
    database.password=P@SSW0rd1
  database.url: "https://changed-server.somewhere.come:3306"
  database.password: "P@SSW0rd1"
