# apiVersion: v1
# kind: Secret
# metadata:
#   name: aws-credentials
# data:
#   accessKey: MTIzNDU2Nzg5MAo=
#   secretKey: MTIzNAo=
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
stringData:
  accessKey: "12345678"
  secretKey: "1234"
