apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
spec:
  template:
    spec:
      containers:
        - name: long-job
          image: python
          command: ["python"]
          args:
            [
              "-c",
              "import time; print('starting'); time.sleep(20); print('done')",
            ]
      restartPolicy: Never
  backoffLimit: 2 # what to do when node fails or some error happens

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-job
spec: # CronJob
  schedule: "* * * * *"
  jobTemplate:
    spec: # Job
      template:
        spec: # Pod
          containers:
            - name: long-job
              image: python
              command: ["python"]
              args:
                [
                  "-c",
                  "import time; print('starting'); time.sleep(20); print('done')",
                ]
          restartPolicy: Never
      backoffLimit: 2 # what to do when node fails or some error happens

